-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC import sys
-- MAGIC
-- MAGIC sys.path.append("/Workspace/Users/bhavik.bhatt@databricks.com/MMA Enrichment")

-- COMMAND ----------

-- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

USE CATALOG `mma_fe_innovation`;
USE SCHEMA `mma`;

SELECT * from `medical_orders_silver`;

-- COMMAND ----------

CREATE OR REFRESH MATERIALIZED VIEW device_unit_prices
AS
SELECT
  device_name,
  CAST(
    1 + FLOOR(POWER(RAND(), 3) * 999)
    AS INT
  ) AS unit_price
FROM (
  SELECT DISTINCT device_name
  FROM mma_fe_innovation.mma.medical_orders_silver
);
